### ISSUE TITLE
Build failure in lib_ui due to empty ic_launcher.xml in tag 4.2.1

### ISSUE THREAD

**Issue by akihin** [NordicSemiconductor/Android-nRF-Toolbox#182]
Hi there,

I ran into a small build issue while working with tag 4.2.1 and wanted to report it.

Problem:
When checking out and building from tag 4.2.1, the CompileLibraryResourcesTask fails for lib_ui.

```
Execution failed for task ':lib_ui:compileDebugLibraryResources'.
> A failure occurred while executing com.android.build.gradle.tasks.CompileLibraryResourcesTask$CompileLibraryResourcesAction
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
         > Resource compilation failed (Failed to compile resource file: ...\nrftoolbox\lib_ui\build\intermediates\packaged_res\debug\packageDebugResources\mipmap-anydpi-v26\ic_launcher.xml: . Cause: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
           Message: 途中でファイルの末尾に達しました。). Check logs for more details.
```

Cause:
The failure is caused by an empty "lib_ui/src/main/res/mipmap-anydpi-v26/ic_launcher.xml". Since the file is empty, the XML parser throws an exception during the build process.

Workaround:
I confirmed that the build completes successfully after manually deleting this empty file.

Suggestion:
If ic_launcher.xml is no longer in use and just remains for historical reasons, would it be possible to remove it from the repository?

Environment:
+ OS: Windows 11 Pro 24H2 (Build 26100.7462)
+ IDE: Android Studio Panda 1 | 2025.3.1 Patch 1

Many Thanks.
